server {
    listen 80;
    server_name onyx.rope.ericngigi.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name onyx.rope.ericngigi.com;

    ssl_certificate /etc/letsencrypt/live/onyx.rope.ericngigi.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/onyx.rope.ericngigi.com/privkey.pem;

    root /var/www/fdroid/repo;

    location / {
        index index.html;
        try_files $uri $uri/ =404;
    }

    # Serve APK files with correct MIME type
    location ~* \.apk$ {
        root /var/www;
        add_header Content-Type application/vnd.android.package-archive;
        add_header Content-Disposition "attachment; filename=$upstream_http_x_filename";
    }

    # Suppress favicon 404
    location = /favicon.ico {
        log_not_found off;
        access_log off;
        return 204;
    }

    location ~* \.(yml|jks|p12)$ {
        deny all;
        return 403;
    }

    # --------------------------------------------------------
    # Limits & Logs
    # --------------------------------------------------------
    client_max_body_size 20M;

    access_log /var/log/nginx/onyx.rope.ericngigi.access.log;
    error_log  /var/log/nginx/onyx.rope.ericngigi.error.log;
}
