server {
    listen 80;
    server_name onyx.rope.ericngigi.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name onyx.rope.ericngigi.com;

    ssl_certificate /etc/letsencrypt/live/onyx.rope.ericngigi.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/onyx.rope.ericngigi.com/privkey.pem;

    root /var/www/fdroid;

    # Serve the main repo
    location /fdroid/repo {
        alias /var/www/fdroid/repo;
        autoindex on;
        add_header Access-Control-Allow-Origin *;
    }

    # Specifically allow the icons folder
    location /fdroid/repo/icons {
        alias /var/www/fdroid/repo/icons;
        add_header Access-Control-Allow-Origin *;
        expires 7d;
    }

    # --------------------------------------------------------
    # Limits & Logs
    # --------------------------------------------------------
    client_max_body_size 20M;

    access_log /var/log/nginx/onyx.rope.ericngigi.access.log;
    error_log  /var/log/nginx/onyx.rope.ericngigi.error.log;
}
